version: 0.1
phases:
  install:
    commands:
      - aws s3 mb s3://mcs.codepipeline --region us-east-1
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket bucket-name 
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml