version: 0.1
phases:
  install:
    commands:
      - pip install --upgrade pip
      - pip install aws-xray-sdk -t _lambda/MCSdisableRule/vendored/.
      - pip install aws-xray-sdk -t _lambda/MCSenableRule/vendored/.
      - pip install aws-xray-sdk -t _lambda/MCSFirestCall/vendored/.
      - pip install aws-xray-sdk -t _lambda/MCSgetSchedule/vendored/.
      - pip install aws-xray-sdk -t _lambda/MCSsetSchedule/vendored/.
      - bash ./_lambda/build.sh
      - aws s3 cp ./index.html s3://${MCS_BUCKET_NAME}/ --acl public-read
      - aws s3 cp ./_js/getSchedule.js s3://${MCS_BUCKET_NAME}&"/_js"/ --acl public-read


  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo echo Nothing to do in the build phase...
  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  type: zip
  files:
    - sam-output.yaml
