version: 0.1
phases:
  install:
    commands:
      - bash ./_lambda/build.sh
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo echo Nothing to do in the build phase...
  post_build:
    commands:
      - echo Build completed on 'date'

artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
